/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;



import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import controller.Vendas;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.dao.VendasDAO;

/**
 *
 * @author thiag
 */
public class ViewVendas extends javax.swing.JFrame {
     private String data;

    /**
     * Creates new form ViewPrincipal
     */
    public ViewVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblCliente = new javax.swing.JLabel();
        LbDtFaturamento = new javax.swing.JLabel();
        LbVlrNotaFiscal = new javax.swing.JLabel();
        TxtCliente = new javax.swing.JTextField();
        TxtDtFatura = new javax.swing.JFormattedTextField();
        LbVlrParcela = new javax.swing.JLabel();
        TxtVlrParcela = new javax.swing.JTextField();
        BtnSalvar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LbNumParcls = new javax.swing.JLabel();
        TxtNmrPrcl = new javax.swing.JTextField();
        TxtValorNF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblCliente.setText("Cliente:");

        LbDtFaturamento.setText("Data do Faturamento:");

        LbVlrNotaFiscal.setText("Valor da Nota Fiscal:");

        try {
            TxtDtFatura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtDtFatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDtFaturaKeyPressed(evt);
            }
        });

        LbVlrParcela.setText("Valor das Parcelas:");

        TxtVlrParcela.setEditable(false);

        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Cadastrar Venda");

        LbNumParcls.setText("Número de Parcelas:");

        TxtNmrPrcl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNmrPrclKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblCliente)
                            .addComponent(LbDtFaturamento)
                            .addComponent(LbVlrNotaFiscal)
                            .addComponent(LbVlrParcela))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtVlrParcela, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(TxtDtFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtValorNF))
                                .addGap(18, 18, 18)
                                .addComponent(LbNumParcls)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNmrPrcl)))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCliente)
                    .addComponent(TxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDtFaturamento)
                    .addComponent(TxtDtFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbVlrNotaFiscal)
                    .addComponent(LbNumParcls)
                    .addComponent(TxtNmrPrcl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtValorNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbVlrParcela)
                    .addComponent(TxtVlrParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnCancelar))
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        VendasDAO dao = new VendasDAO();
        Vendas vnd = new Vendas();
        vnd.setCliente(TxtCliente.getText());
        vnd.getData();
        vnd.setVlrNotaFiscal(Double.parseDouble(TxtValorNF.getText()));
        vnd.setVlrParcela(Double.parseDouble(TxtValorNF.getText()), Integer.parseInt(TxtNmrPrcl.getText()));
        vnd.setNmrDeParcela(Integer.parseInt(TxtNmrPrcl.getText()));
        
        dao.create(vnd);
        new ViewPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
          System.exit(0);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void TxtNmrPrclKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNmrPrclKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Vendas vnd = new Vendas();
            
            vnd.setVlrParcela(Double.parseDouble(TxtValorNF.getText()), Integer.parseInt(TxtNmrPrcl.getText()));
            TxtVlrParcela.setText(""+NumberFormat.getCurrencyInstance().format(vnd.getVlrParcela()));
            
        }
    }//GEN-LAST:event_TxtNmrPrclKeyPressed

    private void TxtDtFaturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDtFaturaKeyPressed
        // TODO add your handling code here:
       data = TxtDtFatura.getText();
       
    }//GEN-LAST:event_TxtDtFaturaKeyPressed

/**/
    /**
     * @param args the command line arguments
     * @throws java.text.ParseException
     */
    public static void main(String args[]) throws ParseException {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewVendas().setVisible(true);
        });
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cal = Calendar.getInstance();
        cal.setTime(formatter.parse(data));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JLabel LbDtFaturamento;
    private javax.swing.JLabel LbNumParcls;
    private javax.swing.JLabel LbVlrNotaFiscal;
    private javax.swing.JLabel LbVlrParcela;
    private javax.swing.JLabel LblCliente;
    private javax.swing.JTextField TxtCliente;
    private javax.swing.JFormattedTextField TxtDtFatura;
    private javax.swing.JTextField TxtNmrPrcl;
    private javax.swing.JTextField TxtValorNF;
    private javax.swing.JTextField TxtVlrParcela;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
