package br.com.pacotes.entidade;
// Generated 06/10/2017 00:25:07 by Hibernate Tools 4.3.1



/**
 * Trabalho generated by hbm2java
 */
public class Trabalho  implements java.io.Serializable {


     private Integer idSpring;
     private String nome;
     private String sobrenome;
     private String nascimento;
     private String sexo;
     private String telefone;
     private String endereco;

    public Trabalho() {
    }

    public Trabalho(String nome, String sobrenome, String nascimento, String sexo, String telefone, String endereco) {
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.nascimento = nascimento;
       this.sexo = sexo;
       this.telefone = telefone;
       this.endereco = endereco;
    }
   
    public Integer getIdSpring() {
        return this.idSpring;
    }
    
    public void setIdSpring(Integer idSpring) {
        this.idSpring = idSpring;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getNascimento() {
        return this.nascimento;
    }
    
    public void setNascimento(String nascimento) {
        this.nascimento = nascimento;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }




}


